language: generic

branches:
  only:
    - master

git:
  depth: 1

os:
  - linux
  - osx

sudo: false
osx_image: xcode8

env:
  global:
    - MAKE="make -j8"
    - R_LIBS_USER=${HOME}/R/library
    - APM_TEST_PACKAGES="language-latex pdf-view"
  matrix:
    - TEX_DIST=texlive ATOM_CHANNEL=stable
    - TEX_DIST=texlive ATOM_CHANNEL=beta

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-recommended

cache:
  directories:
    - ${R_LIBS_USER}

script: ./script/cibuild

notifications:
  email:
    on_success: never
    on_failure: change
